services:
  # ----------------- Django -----------------
  django:
    build: .
    container_name: django_app2
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8007"
    ports:
      - "8007:8007"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  # ----------------- Postgres Database -----------------
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: djredceldocker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: imrandell
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  # ----------------- Redis -----------------
  redis:
    image: redis:7-alpine
    container_name: redis2 # service name is redis2 so in settings also we need to specify
    ports:
      - "6379:6379"

  # ----------------- Celery Worker -----------------
  celery:
    build: .
    container_name: celery_worker2
    command: celery -A DjRedCleDockerJenkins worker -l info
    volumes:
      - .:/app
    depends_on:
      - django
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1

  # ----------------- Celery Beat -----------------
  celery-beat:
    build: .
    container_name: celery_beat2
    command: celery -A DjRedCleDockerJenkins beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - django
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1

  # ----------------- Flower Dashboard -----------------
  flower:
    build: .
    container_name: flower2
    command: celery -A DjRedCleDockerJenkins flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DJANGO_SETTINGS_MODULE=DjRedCleDockerJenkins.settings

  # ----------------- Nginx -----------------
  nginx:
    image: nginx:alpine
    container_name: nginx2
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./app/static:/app/static
      - ./app/media:/app/media
      
    ports:
      - "80:80"
    depends_on:
      - django
    